name: Github CI - Pull request

on: [pull_request, workflow_call]

jobs:
  tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
