name: Github CI - Pull request

on: [push]

jobs:
  tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker
        run: |
          docker build --target=build -t my-service:test .
          docker build --target=service-final -t my-service:finale-test .