name: Playground

on:
  push:

jobs:
  download:
    runs-on: ubuntu-latest
    uses: Vertygo/ga-test/.github/workflows/test.yml@v1
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2

    #   - name: Echo
    #     run: echo "Test!"