name: Playground

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/test.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
