name: Github CI - Publish

on:
  push:
    branches:
      - main
 
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        # run: echo "$(git rev-parse --short HEAD)" >> 

      - name: Tag and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vertygo/${{ github.event.repository.name }}:${{ github.ref_name }}-${{ env.IMAGE_TAG }}
