name: Github CI - Publish

on:
  push:
 
jobs:
  test_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate image tag
        env:
          IMAGE_TAG: ${{ github.ref_name/\//- }}
        run: |
          echo $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
