name: Playground

on:
  push:

jobs:
  uses: .github/workflows/test.yml@v1
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Test!"