name: Github CI - Publish

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+*' # we have multiple tag formats X.X.X, vX.X.X, vX.X.X-some-info
 
jobs:
  build_run_tests:
    name: Build and run tests
    uses: ./.github/workflows/build.yml

  publish_docker_image:
    needs: build_run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Tag and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          target: final
          push: true
          tags: |
            eu.gcr.io/dev-econo-cm/${{ github.event.repository.name }}:${{ github.ref_name }}-$(git rev-parse --short HEAD)
