name: Playground

on:
  push:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call other wf
        uses: ./.github/workflows/test.yml@main

      - name: Echo
        run: echo "Test!"