name: Github CI - Publish

on: [pull_request]
 
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Tag and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          target: final
          push: true
          tags: |
            eu.gcr.io/dev-econo-cm/${{ github.event.repository.name }}:${{ github.ref_name }}-$(git rev-parse --short HEAD)
