name: Playground

on:
  push:

jobs:
  uses: Vertygo/ga-test/.github/workflows/test.yml
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Test!"