name: Github CI - Publish

on: [pull_request]
 
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and publish
        uses: docker/build-push-action@v2
        env:
          GIT_COMMIT: $(git rev-parse --short HEAD)
        with:
          context: .
          push: true
          tags: vertygo/${{ github.event.repository.name }}:${{ github.ref_name }}-${{ env.GIT_COMMIT }}
