name: Github CI - Publish

on:
  push:

jobs:
  publish_docker_image:
    name: Publish docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate image tag
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          IMAGE_TAG=${IMAGE_TAG/[^a-z0-9]/-}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "$IMAGE_TAG"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vertygo/ga-test:${{ env.IMAGE_TAG }}
