name: Github CI - Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_docker_image:
    name: Publish docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate image tag
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          echo $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.DEVECONOCM_GCR_RW }}

      - name: Tag and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eu.gcr.io/dev-econo-cm/mobile-notification-service:${{ env.IMAGE_TAG }}
