name: test

on: [workflow_call, pull_request]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate image tag
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          IMAGE_TAG=${IMAGE_TAG/[^a-z0-9]/-}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "$IMAGE_TAG"
